solution hw-HB-01
RomanHreits/cinema pull request #1
Opened 2020-09-30 09:10 UTC by RomanHreits

2020-09-30 09:56 UTC, andriylagun approved these changes
Well done. Minor comments

2020-09-30 09:56 UTC, andriylagun commented on .travis.yml
> +    - $HOME/.m2
Add empty line

2020-09-30 09:56 UTC, andriylagun commented on src/main/resources/log4j2.xml
> +</Configuration>
same

2020-09-30 09:56 UTC, andriylagun commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
emptyline

2020-09-30 15:31 UTC, KseniiaMakarova requested changes

2020-09-30 15:31 UTC, KseniiaMakarova commented on src/main/java/com/cinema/exceptions/DataProcessingException.java
> +    private String message;
do we need this field?

2020-09-30 15:31 UTC, KseniiaMakarova commented on src/main/java/com/cinema/util/HibernateUtil.java
> +    public static SessionFactory factory = initSessionFactory();
```suggestion
    private static SessionFactory factory = initSessionFactory();
```

2020-09-30 15:31 UTC, KseniiaMakarova commented on src/main/resources/hibernate.cfg.xml
> +        <property name="connection.url">jdbc:mysql://localhost/cinema?serverTimezone=UTC</property>
does it use 3306 by default?

2020-09-30 15:31 UTC, KseniiaMakarova commented on pom.xml
> +            <plugin>
let's add `<pluginManagement>` block

2020-09-30 20:08 UTC, RomanHreits commented on src/main/resources/hibernate.cfg.xml
> +        <property name="connection.url">jdbc:mysql://localhost/cinema?serverTimezone=UTC</property>
і так все працювало, але я добавив

2020-09-30 20:08 UTC, RomanHreits commented on src/main/java/com/cinema/util/HibernateUtil.java
> +    public static SessionFactory factory = initSessionFactory();
done

2020-09-30 20:08 UTC, RomanHreits commented on src/main/java/com/cinema/exceptions/DataProcessingException.java
> +    private String message;
done

2020-09-30 20:08 UTC, RomanHreits commented on pom.xml
> +            <plugin>
done

2020-10-01 07:17 UTC, KseniiaMakarova approved these changes

2020-10-06 14:20 UTC, merged